# Hand-maintained. This file WAS generated by `forktex fsd makefile sync`, but
# the FSD tooling lives in backlog/py/fsd/ and is no longer installed here, so
# the generator cannot run against this repo. Edit this file directly.
# There is no `forktex.json` at the root: the declarative record went to
# backlog/ with the generator. Reviving `fsd/` means re-authoring it.
.DEFAULT_GOAL := help
PROJECT_NAME := forktex
COVERAGE_FLOOR := 94

help: ## Self-documenting target listing
	@grep -E '^[a-zA-Z_@-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2}'

format: ## Source code conforms to a consistent, auto-enforced style
	poetry run python3 -m ruff format src/ tests/

format-check: ## Check formatting without rewriting files
	poetry run python3 -m ruff format --check src/ tests/

lint: ## Static analysis catches bugs, anti-patterns, and security smells
	poetry run python3 -m ruff check src/ tests/

lint-fix: ## Apply every auto-fixable lint finding
	poetry run python3 -m ruff check --fix src/ tests/

typecheck: ## Static type system verifies interface correctness (pyright)
	poetry run python3 -m pyright src/

test: ## Automated tests verify behaviour, with a coverage floor
	@# The floor ratchets: it is the measured figure (95.22%) floored, so coverage
	@# cannot silently drop. Raise it when a pass adds real coverage; never lower
	@# it to make a change pass.
	@# Note: pytest-cov compares the ROUNDED percentage, so 93.6% still satisfies
	@# --cov-fail-under=94 while printing "FAIL ... not reached". Read the number,
	@# not just the word.
	poetry run python3 -m pytest tests/ -q --cov=src/forktex \
		--cov-report=term-missing --cov-fail-under=$(COVERAGE_FLOOR)

audit: ## Scan the project venv for known CVEs in installed deps
	poetry run python3 -m pip_audit --skip-editable --timeout 30

license-check: ## Verify every source file carries the dual-license header (CI gate)
	poetry run python3 scripts/license_headers.py check

license-fix: ## Add or update the dual-license header on every source file
	poetry run python3 scripts/license_headers.py fix

install: ## Bootstrap the project to a runnable state
	poetry install --with dev --all-extras
	@# `poetry install` provisions the venv's own pip, which lags behind and has
	@# repeatedly tripped `make audit` on a pip CVE that has nothing to do with
	@# this project's dependencies. Upgrade it here so bootstrap leaves the venv
	@# in a state `make ci` accepts.
	poetry run python3 -m pip install -q --upgrade "pip>=26.1.2"

build: ## Build sdist + wheel into dist/ and verify metadata with twine check
	rm -rf dist/
	poetry run python3 -m build
	poetry run python3 -m twine check dist/*

smoke: ## Install the BUILT wheel into a throwaway venv and import every extra
	@# `make ci` otherwise only tests the source tree, so a packaging fault is
	@# invisible to it. Importing a module is NOT sufficient to prove its extra
	@# exists — pip only *warns* on an undeclared extra — so this greps for that
	@# warning and fails on it.
	@set -e; \
	WHL=$$(ls dist/forktex-*-py3-none-any.whl 2>/dev/null | head -1); \
	if [ -z "$$WHL" ]; then echo "  no wheel in dist/ — run 'make build' first"; exit 1; fi; \
	PY=$$(poetry run python3 -c 'import sys; print(sys.executable)'); \
	TMP=$$(mktemp -d); trap 'rm -rf $$TMP' EXIT; \
	echo "smoke: base install from $$WHL (interpreter $$PY)"; \
	$$PY -m venv $$TMP/base >/dev/null; \
	$$TMP/base/bin/pip install -q "$$WHL" 2>&1 | tee $$TMP/base.log; \
	! grep -q "does not provide the extra" $$TMP/base.log; \
	for m in log error types iso database cache graph; do \
		$$TMP/base/bin/python -c "import forktex.$$m" || { echo "  ✗ base import forktex.$$m"; exit 1; }; \
	done; \
	echo "  base modules import"; \
	for x in vault storage queue vector store; do \
		$$PY -m venv $$TMP/$$x >/dev/null; \
		$$TMP/$$x/bin/pip install -q "$$WHL[$$x]" 2>&1 | tee $$TMP/$$x.log; \
		if grep -q "does not provide the extra" $$TMP/$$x.log; then echo "  ✗ [$$x] undeclared"; exit 1; fi; \
		$$TMP/$$x/bin/python -c "import forktex.$$x" || { echo "  ✗ [$$x] import"; exit 1; }; \
		echo "  [$$x] OK"; \
	done; \
	echo "smoke: every extra resolves and delivers a working module"

publish-test: ## Upload dist/ to TestPyPI for rehearsal
	poetry run python3 -m twine upload -r testpypi dist/*

publish: ## Upload dist/ to production PyPI (irreversible per-version)
	poetry run python3 -m twine upload dist/*

clean: ## Build artifacts and caches removable from project tree
	find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null; true
	find . -type d -name .pytest_cache -exec rm -rf {} + 2>/dev/null; true
	find . -type d -name .ruff_cache -exec rm -rf {} + 2>/dev/null; true
	find . -type d -name dist -exec rm -rf {} + 2>/dev/null; true
	find . -type d -name "*.egg-info" -exec rm -rf {} + 2>/dev/null; true
	find . -type d -name htmlcov -exec rm -rf {} + 2>/dev/null; true
	find . -type f -name .coverage -delete 2>/dev/null; true

ci: ## Aggregate quality gate before publish
	@$(MAKE) format-check
	@$(MAKE) lint
	@$(MAKE) license-check
	@$(MAKE) typecheck
	@$(MAKE) audit
	@$(MAKE) test
	@$(MAKE) build
	@$(MAKE) smoke
	@echo ''
	@echo 'CI passed for $(PROJECT_NAME) — safe to: make publish-test  /  make publish'

.PHONY: help format format-check lint lint-fix typecheck test audit license-check \
	license-fix install build smoke publish-test publish clean ci
