# Copyright (C) 2026 FORKTEX S.R.L.
#
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-ForkTex-Commercial
#
# This file is part of ForkTex Python.
#
# For commercial licensing -- including use in proprietary products, SaaS
# deployments, or any context where AGPL obligations cannot be met -- you
# MUST obtain a commercial license from FORKTEX S.R.L. (info@forktex.com).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""Tests for forktex.runtime.lifecycle: install + register + deactivate."""

import pytest

from forktex.runtime import instance as _instance
from forktex.runtime import lifecycle


pytestmark = pytest.mark.usefixtures("isolated_home")


def test_install_global_writes_gitignore(isolated_home):
    lifecycle.install_global()
    gi = isolated_home / ".forktex" / ".gitignore"
    assert gi.is_file()
    content = gi.read_text()
    assert "Auto-generated by forktex" in content


def test_install_project_writes_skeleton(project_root):
    lifecycle.install_project(project_root)
    fdir = project_root / ".forktex"
    assert fdir.is_dir()
    assert (fdir / ".version").is_file()
    assert (fdir / ".gitignore").is_file()
    inner = (fdir / ".gitignore").read_text()
    assert "*" in inner
    assert "!.gitignore" in inner
    assert "!.version" in inner


def test_install_project_idempotent(project_root):
    lifecycle.install_project(project_root)
    first = (project_root / ".forktex" / ".gitignore").read_text()
    lifecycle.install_project(project_root)
    second = (project_root / ".forktex" / ".gitignore").read_text()
    assert first == second


def test_ensure_runtime_creates_instance(project_root, monkeypatch):
    monkeypatch.chdir(project_root)
    rec = lifecycle.ensure_runtime(needs_project=True, kind="test")
    assert rec is not None
    assert rec.kind == "test"
    assert rec.project_root == str(project_root.resolve())
    # Persisted to host instances dir.
    files = list(_instance.global_instances_dir().glob("*.json"))
    assert any(p.stem == rec.run_id for p in files)
    lifecycle.deactivate(rec)


def test_ensure_runtime_fails_outside_project_when_required(orphan_dir, monkeypatch):
    monkeypatch.chdir(orphan_dir)
    rec = lifecycle.ensure_runtime(needs_project=True, kind="test")
    # The function returns None when no project is found and one is required.
    assert rec is None


def test_ensure_runtime_skips_install_outside_project(orphan_dir, monkeypatch):
    monkeypatch.chdir(orphan_dir)
    rec = lifecycle.ensure_runtime(needs_project=False, kind="test")
    # The runtime still emits a host-only record (no project_root).
    assert rec is not None
    assert rec.project_root is None
    lifecycle.deactivate(rec)


def test_deactivate_marks_stopped(project_root, monkeypatch):
    monkeypatch.chdir(project_root)
    rec = lifecycle.ensure_runtime(needs_project=True, kind="test")
    assert rec is not None
    rec_path = _instance.global_instances_dir() / f"{rec.run_id}.json"

    lifecycle.deactivate(rec)
    import json

    data = json.loads(rec_path.read_text())
    assert data["status"] == "stopped"
    assert data["stopped_at"] is not None


def test_lifecycle_busts_query_cache_on_install(project_root, monkeypatch):
    """Sanity: install_project + ensure_project_dirs side-effects don't
    accidentally invalidate the per-process Graph cache."""
    monkeypatch.chdir(project_root)
    from forktex.graph.query import session_graph

    g1 = session_graph(project_root)
    lifecycle.install_project(project_root)
    g2 = session_graph(project_root)
    assert g1 is g2  # install is idempotent on a fresh project


def test_install_writes_match_structure_spec(project_root):
    """Every file the lifecycle writes should validate against the spec."""
    lifecycle.install_project(project_root)
    from forktex.graph.structure import audit

    results = audit("project", project_root)
    unknown = [r for r in results if r.status == "unknown"]
    assert unknown == [], (
        f"unknown entries after install: {[r.rel_path for r in unknown]}"
    )
