# Copyright (C) 2026 FORKTEX S.R.L.
#
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-ForkTex-Commercial
#
# This file is part of ForkTex Python.
#
# For commercial licensing -- including use in proprietary products, SaaS
# deployments, or any context where AGPL obligations cannot be met -- you
# MUST obtain a commercial license from FORKTEX S.R.L. (info@forktex.com).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""`make sync` codegen — OpenAPI → Python SDK models + TS RTK Query slice.

Reads the committed ``openapi.json`` (regenerated by ``tools.export_openapi``)
and produces:

- ``codegen/build/models.py`` — Pydantic v2 models (datamodel-code-generator).
- ``client/src/api/grid.ts`` — RTK Query slice + hooks (@rtk-query/codegen-openapi
  via npx; requires Node).

Each generator is optional: a missing toolchain is reported, not fatal, so the
loop degrades gracefully.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OPENAPI = ROOT / "openapi.json"
BUILD = Path(__file__).resolve().parent / "build"


def _python_models() -> bool:
    if shutil.which("datamodel-codegen") is None:
        print(
            "skip: datamodel-code-generator not installed (pip install datamodel-code-generator)"
        )
        return False
    BUILD.mkdir(exist_ok=True)
    subprocess.run(
        [
            "datamodel-codegen",
            "--input",
            str(OPENAPI),
            "--input-file-type",
            "openapi",
            "--output-model-type",
            "pydantic_v2.BaseModel",
            "--output",
            str(BUILD / "models.py"),
        ],
        check=True,
    )
    print(f"wrote {BUILD / 'models.py'}")
    return True


def _ts_rtk() -> bool:
    if shutil.which("npx") is None:
        print("skip: npx/Node not available — TS RTK slice not generated")
        return False
    config = Path(__file__).resolve().parent / "rtk.config.cjs"
    try:
        subprocess.run(
            ["npx", "-y", "@rtk-query/codegen-openapi", str(config)],
            check=True,
            cwd=config.parent,
        )
    except subprocess.CalledProcessError as exc:
        print(
            f"skip: TS RTK generation failed ({exc}); run `make sync` where npm can fetch the generator"
        )
        return False
    print("wrote client/src/api/grid.ts")
    return True


def main() -> None:
    if not OPENAPI.exists():
        print(
            f"missing {OPENAPI} — run: python -m tools.export_openapi > openapi.json",
            file=sys.stderr,
        )
        raise SystemExit(1)
    _python_models()
    _ts_rtk()


if __name__ == "__main__":
    main()
