# Copyright (C) 2026 FORKTEX S.R.L.
#
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-ForkTex-Commercial
#
# This file is part of ForkTex Python.
#
# For commercial licensing -- including use in proprietary products, SaaS
# deployments, or any context where AGPL obligations cannot be met -- you
# MUST obtain a commercial license from FORKTEX S.R.L. (info@forktex.com).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""Render Structurizr DSL from a ForkTex graph (via the C4 projection)."""

from __future__ import annotations

import re

from forktex.architecture.models import Workspace
from forktex.graph.models import Graph
from forktex.graph.views.c4 import graph_to_workspace


_DSL_ID = re.compile(r"[^A-Za-z0-9_]")


def _did(s: str) -> str:
    cleaned = _DSL_ID.sub("_", s)
    if cleaned and cleaned[0].isdigit():
        cleaned = "_" + cleaned
    return cleaned or "id"


def _q(s: str) -> str:
    return s.replace('"', '\\"')


def _render_workspace(workspace: Workspace, generated_at: str, scope: str) -> str:
    lines: list[str] = [
        f'workspace "{_q(workspace.name)}" "{_q(workspace.description)}" {{',
        f"    # Generated by ForkTex (graph scope: {scope}, at: {generated_at})",
        "    model {",
        "        !identifiers hierarchical",
        "",
    ]

    for system in workspace.systems:
        sid = _did(system.id)
        lines.append(
            f'        {sid} = softwareSystem "{_q(system.name)}" '
            f'"{_q(system.description)}" {{'
        )
        for container in system.containers:
            cid = _did(container.id)
            lines.append(
                f'            {cid} = container "{_q(container.name)}" '
                f'"{_q(container.description)}" "{_q(container.tech_summary)}"'
                f" {{"
            )
            for comp in container.components:
                lines.append(
                    f"                {_did(comp.id)} = component "
                    f'"{_q(comp.name)}" "{_q(comp.description)}"'
                )
            lines.append("            }")
        lines.append("        }")
        lines.append("")

    lines.extend(["    }", ""])
    lines.append("    views {")
    if len(workspace.systems) > 1:
        lines.extend(
            [
                "        systemLandscape {",
                "            include *",
                "            autolayout lr",
                "        }",
            ]
        )
    for system in workspace.systems:
        lines.extend(
            [
                f"        container {_did(system.id)} {{",
                "            include *",
                "            autolayout lr",
                "        }",
            ]
        )
    lines.extend(["    }", "}"])
    return "\n".join(lines) + "\n"


def render_dsl(graph: Graph) -> str:
    """Return Structurizr DSL text for *graph*."""
    workspace = graph_to_workspace(graph)
    return _render_workspace(workspace, graph.meta.generated_at, graph.meta.scope)
