#!/usr/bin/env python3
"""Sync generated Pydantic models from the Intelligence API's OpenAPI spec.

Usage:
    # From a running server:
    python scripts/sync_openapi.py http://localhost:8000

    # From a spec file:
    python scripts/sync_openapi.py --file ../intelligence/docs/openapi.json

    # Dry-run (show diff without writing):
    python scripts/sync_openapi.py http://localhost:8000 --dry-run

This script fetches the OpenAPI spec, extracts all component schemas,
and regenerates src/forktex/intelligence/client/generated/__init__.py
with typed Pydantic models. It preserves the same structure as a manual
codegen run but keeps the models co-located with the client.

Designed to run in CI or as a pre-commit hook to keep client and server
in sync.
"""

from __future__ import annotations

import argparse
import json
import sys
import textwrap
from pathlib import Path
from typing import Any

# Type mapping from JSON Schema types to Python types
JSON_TO_PYTHON: dict[str, str] = {
    "string": "str",
    "integer": "int",
    "number": "float",
    "boolean": "bool",
    "object": "dict[str, Any]",
    "array": "list[Any]",
}

HEADER = '''"""Auto-generated Pydantic models for the ForkTex Intelligence API.

Source: {source}
Generated by: scripts/sync_openapi.py
Do NOT edit manually — regenerate with: python scripts/sync_openapi.py {source}
"""

from __future__ import annotations

import time
from typing import Any, Optional

from pydantic import BaseModel, Field
'''


def fetch_spec(url: str) -> dict[str, Any]:
    """Fetch OpenAPI spec from a running server."""
    import httpx
    resp = httpx.get(f"{url.rstrip('/')}/openapi.json", timeout=10)
    resp.raise_for_status()
    return resp.json()


def load_spec(path: str) -> dict[str, Any]:
    """Load OpenAPI spec from a file."""
    return json.loads(Path(path).read_text())


def resolve_type(prop: dict[str, Any], required: bool) -> tuple[str, str | None]:
    """Resolve a JSON Schema property to a Python type annotation and default.

    Returns (type_str, default_str_or_None).
    """
    if "$ref" in prop:
        ref_name = prop["$ref"].split("/")[-1]
        if required:
            return ref_name, None
        return f"Optional[{ref_name}]", "None"

    json_type = prop.get("type", "string")

    if json_type == "array":
        items = prop.get("items", {})
        if "$ref" in items:
            item_type = items["$ref"].split("/")[-1]
        else:
            item_type = JSON_TO_PYTHON.get(items.get("type", "string"), "Any")
        list_type = f"list[{item_type}]"
        if required:
            return list_type, None
        return f"Optional[{list_type}]", "None"

    # anyOf (union / optional)
    if "anyOf" in prop:
        types = []
        has_null = False
        for variant in prop["anyOf"]:
            if variant.get("type") == "null":
                has_null = True
            elif "$ref" in variant:
                types.append(variant["$ref"].split("/")[-1])
            else:
                types.append(JSON_TO_PYTHON.get(variant.get("type", "string"), "Any"))
        type_str = " | ".join(types) if len(types) > 1 else types[0] if types else "Any"
        if has_null or not required:
            return f"Optional[{type_str}]", "None"
        return type_str, None

    py_type = JSON_TO_PYTHON.get(json_type, "Any")
    if not required:
        return f"Optional[{py_type}]", "None"
    return py_type, None


def generate_model(name: str, schema: dict[str, Any]) -> str:
    """Generate a Pydantic model class from a JSON Schema."""
    lines = []
    desc = schema.get("description", "")
    lines.append(f"\nclass {name}(BaseModel):")
    if desc:
        lines.append(f'    """{desc}"""')
    lines.append("")

    props = schema.get("properties", {})
    required_fields = set(schema.get("required", []))

    if not props:
        lines.append("    pass")
        return "\n".join(lines)

    for field_name, field_schema in props.items():
        is_required = field_name in required_fields
        type_str, default = resolve_type(field_schema, is_required)

        # Special defaults
        field_desc = field_schema.get("description", "")
        has_default = "default" in field_schema

        if has_default:
            default_val = field_schema["default"]
            if default_val is None:
                default = "None"
                if "Optional" not in type_str:
                    type_str = f"Optional[{type_str}]"
            elif isinstance(default_val, bool):
                default = str(default_val)
            elif isinstance(default_val, str):
                default = repr(default_val)
            elif isinstance(default_val, (int, float)):
                default = str(default_val)
            elif isinstance(default_val, list):
                default = f"Field(default_factory=list)"
            elif isinstance(default_val, dict):
                default = f"Field(default_factory=dict)"

        if default is not None:
            lines.append(f"    {field_name}: {type_str} = {default}")
        else:
            lines.append(f"    {field_name}: {type_str}")

    return "\n".join(lines)


def generate_models(spec: dict[str, Any], source: str) -> str:
    """Generate the full models file from an OpenAPI spec."""
    schemas = spec.get("components", {}).get("schemas", {})
    output = HEADER.format(source=source)

    # Skip validation-related schemas
    skip = {"HTTPValidationError", "ValidationError"}

    # Order: simpler models first, then models that reference them
    # Simple heuristic: sort by number of $ref in properties
    def ref_count(name: str) -> int:
        s = schemas.get(name, {})
        count = 0
        for p in s.get("properties", {}).values():
            if "$ref" in p:
                count += 1
            if "items" in p and "$ref" in p["items"]:
                count += 1
        return count

    ordered = sorted(
        [n for n in schemas if n not in skip],
        key=lambda n: (ref_count(n), n),
    )

    for name in ordered:
        schema = schemas[name]
        output += "\n" + generate_model(name, schema) + "\n"

    return output


def main() -> None:
    parser = argparse.ArgumentParser(description="Sync Intelligence API models from OpenAPI spec")
    parser.add_argument("source", nargs="?", default="http://localhost:8000",
                        help="Server URL or --file path")
    parser.add_argument("--file", "-f", help="Path to openapi.json file")
    parser.add_argument("--dry-run", action="store_true", help="Print output without writing")
    parser.add_argument("--output", "-o", default=None,
                        help="Output path (default: src/forktex/intelligence/client/generated/__init__.py)")
    args = parser.parse_args()

    if args.file:
        spec = load_spec(args.file)
        source = args.file
    else:
        source = args.source
        try:
            spec = fetch_spec(source)
        except Exception as e:
            print(f"Error fetching spec from {source}: {e}", file=sys.stderr)
            sys.exit(1)

    output = generate_models(spec, source)

    if args.dry_run:
        print(output)
        return

    out_path = Path(args.output) if args.output else (
        Path(__file__).parent.parent / "src" / "forktex" / "intelligence" / "client" / "generated" / "__init__.py"
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)

    # Check if content changed
    if out_path.exists() and out_path.read_text() == output:
        print(f"No changes needed: {out_path}")
        return

    out_path.write_text(output)
    print(f"Updated {out_path} ({len(spec.get('components', {}).get('schemas', {}))} schemas)")


if __name__ == "__main__":
    main()
