# Copyright (C) 2026 FORKTEX S.R.L.
#
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-ForkTex-Commercial
#
# This file is part of ForkTex Python.
#
# For commercial licensing -- including use in proprietary products, SaaS
# deployments, or any context where AGPL obligations cannot be met -- you
# MUST obtain a commercial license from FORKTEX S.R.L. (info@forktex.com).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""Auto-install + instance-register lifecycle for every forktex invocation.

Called from decorators (`@needs_project`, `@long_running`) at the top of
each Click subcommand callback. Skips on `--help` / `--version` because
Click short-circuits before the callback runs.

Three .gitignore points are managed here:

1. ``<project_root>/.gitignore`` — managed by ``forktex_cloud.paths.ensure_project_dirs``.
2. ``<root>/.forktex/.gitignore`` — defence-in-depth inside the .forktex/.
3. ``~/.forktex/.gitignore`` — global-scope equivalent.
"""

from __future__ import annotations

import atexit
import logging
import signal
import threading
from pathlib import Path

from forktex_cloud import paths as _cloud_paths

from forktex.core.paths import find_project_root
from forktex.graph.io_proxy import tracked_write
from forktex.runtime import instance as _instance


_log = logging.getLogger("forktex.runtime.lifecycle")


# ── Gitignore content ─────────────────────────────────────────────────────


_INNER_GITIGNORE = """\
# Auto-generated by forktex (forktex-py runtime). Do not edit.
# Belt-and-braces protection: keeps secrets and generated state out of
# git even if the project-root .gitignore is missing the canonical block.
*
!.gitignore
!.version
"""

_GLOBAL_GITIGNORE = """\
# Auto-generated by forktex (forktex-py runtime). Do not edit.
# ~/.forktex/ shouldn't normally be inside any git tree; this file is a
# safety net against a stray `git init` at $HOME.
*
!.gitignore
"""


# ── Auto-install ──────────────────────────────────────────────────────────


def _ensure_inner_gitignore(forktex_dir: Path, *, content: str) -> None:
    """Write ``<forktex_dir>/.gitignore`` if absent or stale."""
    target = forktex_dir / ".gitignore"
    if target.is_file() and target.read_text(encoding="utf-8") == content:
        return
    try:
        tracked_write(
            target,
            content,
            kind="gitignore",
            writer="forktex.runtime.lifecycle",
        )
    except Exception as exc:  # pragma: no cover — non-fatal
        _log.debug("failed to write inner gitignore at %s: %s", target, exc)


def install_project(project_root: Path) -> None:
    """Ensure ``<project_root>/.forktex/`` exists with .version, the canonical
    project-root .gitignore block, and the inner defence-in-depth gitignore."""
    project_root = project_root.resolve()
    _cloud_paths.ensure_project_dirs(project_root)
    _ensure_inner_gitignore(
        _cloud_paths.project_dir(project_root), content=_INNER_GITIGNORE
    )


def install_global() -> None:
    """Ensure ``~/.forktex/`` exists with secure perms + inner gitignore."""
    _cloud_paths.ensure_global_dir()
    _ensure_inner_gitignore(_cloud_paths.global_dir(), content=_GLOBAL_GITIGNORE)


# ── Instance registration ────────────────────────────────────────────────


_active_instances: list[_instance.InstanceRecord] = []
_atexit_registered = False
_signal_handlers_registered = False
_signal_lock = threading.Lock()


def _close_all_active() -> None:
    while _active_instances:
        rec = _active_instances.pop()
        try:
            _instance.close_instance(rec)
        except Exception:  # pragma: no cover
            pass


def _ensure_atexit() -> None:
    global _atexit_registered
    if _atexit_registered:
        return
    atexit.register(_close_all_active)
    _atexit_registered = True


def _ensure_signal_handlers() -> None:
    global _signal_handlers_registered
    with _signal_lock:
        if _signal_handlers_registered:
            return
        if threading.current_thread() is not threading.main_thread():
            return
        for sig in (signal.SIGINT, signal.SIGTERM):
            try:
                prior = signal.getsignal(sig)
                signal.signal(sig, _make_signal_handler(prior))
            except (OSError, ValueError):  # fmt: skip  # pragma: no cover
                continue
        _signal_handlers_registered = True


def _make_signal_handler(prior):
    def _handler(signum, frame):
        _close_all_active()
        if callable(prior) and prior not in (
            signal.SIG_DFL,
            signal.SIG_IGN,
            _handler,
        ):
            try:
                prior(signum, frame)
            except SystemExit:
                raise
            except Exception:  # pragma: no cover
                pass
        # Re-raise as KeyboardInterrupt for SIGINT to keep Click's behaviour.
        if signum == signal.SIGINT:
            raise KeyboardInterrupt

    return _handler


# ── Public API ────────────────────────────────────────────────────────────


def ensure_runtime(
    *,
    needs_project: bool = True,
    long_running: bool = False,
    kind: str = "one-shot",
    project_hint: str | None = None,
) -> _instance.InstanceRecord | None:
    """Auto-install + instance-register for the current invocation.

    Returns the freshly created :class:`InstanceRecord`, or ``None`` if the
    caller said ``needs_project=False`` and we couldn't find one.
    """
    install_global()
    _instance.gc_stale_instances()

    project_root: Path | None = None
    start: Path | None
    if project_hint:
        start = Path(project_hint).resolve()
    else:
        start = Path.cwd().resolve()

    found = find_project_root(start)
    if found is not None:
        project_root = found
        install_project(project_root)
    elif needs_project:
        # Caller asked for a project; we can't find one. Don't create
        # the record — the decorator should error out before this
        # point in practice, but guard anyway.
        return None

    rec = _instance.create_instance(
        kind=kind,
        project_root=project_root,
        long_running=long_running,
    )
    _active_instances.append(rec)
    _ensure_atexit()
    _ensure_signal_handlers()
    return rec


def deactivate(rec: _instance.InstanceRecord) -> None:
    """Mark an instance stopped and remove it from the active list."""
    try:
        _active_instances.remove(rec)
    except ValueError:
        pass
    _instance.close_instance(rec)
